title: Jose's Portfolio
name:
null.logo: <img src="mugshot.jpeg" alt="My Photo" Width="200px">
remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
